version: '2.1'
services:
  nginx-mailcow:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-mailcow.entrypoints=web"
      - "traefik.http.routers.nginx-mailcow.rule=HostRegexp(`{host:(autodiscover|autoconfig|webmail|mail|email).+}`)"
      - "traefik.http.middlewares.nginx-mailcow-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nginx-mailcow.middlewares=nginx-mailcow-https-redirect"
      - "traefik.http.routers.nginx-mailcow-secure.entrypoints=websecure"
      - "traefik.http.routers.nginx-mailcow-secure.rule=Host(`mail.localhost`)" # YOUR EMAIL SUBDMAIN
      - "traefik.http.routers.nginx-mailcow-secure.tls=true"
      - "traefik.http.routers.nginx-mailcow-secure.service=nginx-mailcow"
      - "traefik.http.routers.nginx-mailcow-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.nginx-mailcow.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      proxy:

  #This is extract traefik acme to certs for other container if nedded:
  traefik-certs-dumper:
    image: ghcr.io/kereis/traefik-certs-dumper:latest
    container_name: traefik-certs-dumper
    restart: unless-stopped
    command: --restart-containers mailcowdockerized_postfix-mailcow_1,mailcowdockerized_dovecot-mailcow_1
    volumes:
      #mount the folder which contains Traefik's `acme.json' file
      #in this case Traefik is started from its own docker-compose in ../traefik
      - "/etc/localtime:/etc/localtime:ro"
      - "/root/traefik/letsencrypt:/traefik:ro"  # Ensure this matches the Traefik volume
      #mount mailcow's SSL folder
      - "certs:/output"
    environment:
      - DOMAIN=mail.localhost # YOUR EMAIL SUBDOMAIN HERE

networks:
  proxy: # YOUR TRAEFIK NETWORK HERE
    external: true
volumes:
  certs: