# NOTE: This docker-compose.yml is meant to be just an example guideline
# on how you can achieve the same. It is not intented to run out of the box
# and you must edit the below configurations to suit your needs.

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "9001:9001"
  networks:
    - listmonk
    - proxy
  environment:
    - TZ=Etc/UTC

x-db-defaults: &db-defaults
  image: postgres:13-alpine
  ports:
    - "9432:5432"
  networks:
    - listmonk
    - proxy
  environment:
    - POSTGRES_PASSWORD=listmonk
    - POSTGRES_USER=listmonk
    - POSTGRES_DB=listmonk
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    hostname: listmonk.example.com # Recommend using FQDN for hostname
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.listmonk.rule=Host(`listmonk.example.com`)"
      - "traefik.http.services.listmonk.loadbalancer.server.port=9001"

networks:
  listmonk:
  proxy:
    external: true
volumes:
  listmonk-data: