version: '3.8'
services:
  ghost:
    image: ghost:5-alpine
    restart: always
    environment:
      database__client: mysql
      database__connection__host: cms-ghost-6f80da
      database__connection__user: mysql
      database__connection__password: HP4pf65VzhPKM7qV
      database__connection__database: ghost
      url: http://${GHOST_HOST}
    volumes:
      - ghost:/var/lib/ghost/content
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost.rule=Host(`example.com`)
      - traefik.http.routers.ghost.entrypoints=web
      - traefik.http.services.ghost.loadbalancer.server.port=2368
      - traefik.http.routers.ghost.service=ghost
      - traefik.http.routers.ghost.middlewares=redirect-to-https@file
      - traefik.http.routers.ghostsecure.rule=Host(`example.com`)
      - traefik.http.routers.ghostsecure.entrypoints=websecure
      - traefik.http.services.ghostsecure.loadbalancer.server.port=2368
      - traefik.http.routers.ghostsecure.service=ghostsecure
      - traefik.http.routers.ghostsecure.tls.certresolver=letsencrypt
    networks:
      - dokploy-network
volumes:
  ghost: null
  db: null
networks:
  dokploy-network:
    external: true