services:
  snappymail:
    image: djmaze/snappymail:latest
    ports:
      - 8888:8888
    environment:
      - DEBUG=true
    volumes:
      - snappymail:/var/lib/snappymail
    networks:
      - default
      - dokploy-network
    restart: unless-stopped

  php-fpm-exporter:
    image: hipages/php-fpm_exporter:2.2.0
    ports:
      - '9253:9253'
    environment:
      - PHP_FPM_SCRAPE_URI=tcp://snappymail:9000/status
    networks:
      - default

networks:
  default: null
  dokploy-network:
    external: true

volumes:
  snappymail:
    driver: local