services:
  wordpress-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: Pass12345
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Pass12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy
  
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Pass12345
      WORDPRESS_DB_NAME: wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`example.com`)"  # Change to your domain
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    depends_on:
      - wordpress-db
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - proxy

volumes:
  db_data:
  wordpress_data:

networks:
  proxy:
    external: true
